### ISSUE TITLE
Saving resume points and giving the option to resume from where left off

### ISSUE THREAD

**Issue by raycekar** [cguZZman/script.module.clouddrive.common#6]
A way to save the resume points, so that after selecting a screen resolution, the user (if having it enabled in settings) will then be prompted to either resume or start over. 

![databaseresumepoints](https://user-images.githubusercontent.com/17347780/43996722-8fcaeb8a-9d8e-11e8-8c19-e060d7a07aa2.png)

so far this is as far as I have gotten but figured I'd bring it up cuz I think this would be a nice feature as well.

**Comment by cguZZman** [comment]
I got the idea, and yea it would be nice to have that feature. But I'm more inclined to fix it in the Kodi side.
Is this the way other addons do it?

**Comment by raycekar** [comment]
The main one I found that used this technique was [gdrive](https://github.com/ddurdle/GDrive-for-KODI/blob/49f90ab4db3601a7b728bba1c97cb9390d22ac07/resources/lib/gPlayer.py#L515) and I thought that was a pretty good idea.  What do you mean by fixing it on the Kodi end?  Other idea was to use onPlayBackEnded() but I have not tested to see if you can get the last played time from that.

**Comment by cguZZman** [comment]
I mean this is a Kodi functionality, so I would expect Kodi to handle it. If saving resume points are not working in some scenarios where it should, I was thinking on cloning kodi and try to fix it. That's what I mean.

But if there is a way to fix it within the addon, we can talk about it. 
I like more the idea with events rather than pooling the Player information.
Also I'm wondering where this resume points should be saved. Will be totally handle it by the addon? or there is a way to tell Kodi to save the resume point wherever it's already saving that info for normal files.

**Comment by raycekar** [comment]
Aww I see. After doing a little digging i found [this](https://kodi.wiki/view/HOW-TO:Modify_automatic_watch_and_resume_points) where it talks about the advancedsettings.xml file that has to be created by the user.  You think we could possibly use this in some way?

when I have time Ill mess around with the file and see if kodi handles this itself

**Comment by raycekar** [comment]
Seems that with strm files, Kodi is wanting the addon itself to handle the resume points. 
https://forum.kodi.tv/showthread.php?tid=320240

EDIT: continued looking around and it does in fact look like strm are playlist objects and have to be handled by the addon :/

I am thinking of doing what I have set in the image above and sync it with the kodi database. what do you think?

**Comment by cguZZman** [comment]
I'm currently working on https://github.com/cguZZman/plugin.googledrive/issues/20 and instead of pulling the Player status, a new Player Service was created to subscribe the addon to the Player events. I'll commit the code soon. We can use this new service to track the playing progress and then do the saving stuff. 
Yes I think the progress should be saved to the kodi database so it's transparent for other services like Trakt. I'm not sure it will be accepted by the kodi team tho (saving stuff to kodi's db), I read something about it somewhere, but we can try.

**Comment by fabioneves** [comment]
@cguZZman this issue is for resume points for strm files? I was about to open an issue, but looks like it's already being handled :) 👍

**Comment by cguZZman** [comment]
@fabioneves Yes, this includes resume points for strm files.

@raycekar I committed the code with the Player service. https://github.com/cguZZman/script.module.clouddrive.common/commit/37210effa0bd5bea5e5a3e9ef1b50f3a7942d565.
The idea is to trigger the tracking of the progress in method `onPlayBackStarted` after detecting the current playing is coming from the addon. Then just save it to the db when `onPlayBackEnded` or `onPlayBackStopped` is called.
I'll be researching how to save in kodi's db. If you found something, let me know. Thanks

**Comment by raycekar** [comment]
@cguZZman yeah if I find anything ill let you know.  Ill probably do some research into this this weekend.

**Comment by adrian2095** [comment]
It works when I enter to the tv show folder, but when I press 'Continue Watching' or 'Next Up' of kodi widgets, it doesn't recognise the resume point. Any solution?

**Comment by ntilikp** [comment]
> It works when I enter to the tv show folder, but when I press 'Continue Watching' or 'Next Up' of kodi widgets, it doesn't recognise the resume point. Any solution?

Having the same issue here.  Did you find any solution?
